In [1]:
import torch

In [24]:
x = [i for i in range(1, 6)]

In [25]:
y = [[each] for each in x]

In [26]:
x, y

([1, 2, 3, 4, 5], [[1], [2], [3], [4], [5]])

In [32]:
x = [[1, 2, 3],
     [4, 5],
     [6, 7, 8]]

In [33]:
y = []
print(id(y))
y += [[each] for each in x]
print(id(y))

2450100526656
2450100526656


In [34]:
x, y

([[1, 2, 3], [4, 5], [6, 7, 8]], [[[1, 2, 3]], [[4, 5]], [[6, 7, 8]]])

In [73]:
x = [[1, 2, 3],
     [4, 5],
     [6, 7, 8]]

In [68]:
y = [0] * 3

In [69]:
x, y

([[1, 2, 3], [4, 5], [6, 7, 8]], [0, 0, 0])

In [113]:
x = [[1, 2],
     [4, 5],
     [6, 7]]
tmp = [torch.tensor(each) for each in x]

In [114]:
tmp

[tensor([1, 2]), tensor([4, 5]), tensor([6, 7])]

In [103]:
x = torch.zeros((len(x), len(x[0])))
for i in range(0, 3):
    x[i] = tmp[i]
print(x)

tensor([[1., 2.],
        [4., 5.],
        [6., 7.]])


In [107]:
n = len(x[0])

In [108]:
n

2

In [101]:
tmp = [tmp[0:2], [tmp[2]]]
print(tmp)

[[tensor([1, 2]), tensor([4, 5])], [tensor([6, 7])]]


In [103]:
[word for sentence in tmp for word in sentence]

[tensor([1, 2]), tensor([4, 5]), tensor([6, 7])]

In [114]:
if([1]):
    x = 1
else:
    x = 2
print(x)

1


In [129]:
com_mat = [[0] * 4 for _ in range(0, 4)]

In [130]:
for i in range(0, 4 - 1):
    com_mat[i][i + 1] = 1
    com_mat[i + 1][i] = 1

In [131]:
i += 1
com_mat[i][0] = 1
com_mat[0][i] = 1

In [134]:
del x

In [136]:
if(x is None):
    print(1)
else:
    print(2)

NameError: name 'x' is not defined

In [141]:
[each for each in x]

[tensor([1., 2.]), tensor([4., 5.]), tensor([6., 7.])]

In [149]:
class a():
    def __init__(self, val):
        self.val = val
class A(list[a]):
    def __init__(self, vals):
        self.num = len(vals)
        for i in range(0, self.num):
            self.append(a(vals[i]))

In [150]:
vals = [1, 2, 3]
x = A(vals)

In [151]:
x[0]

In [10]:
x = dict({'':[]})

In [11]:
x

{'': []}

In [14]:
x['grad']=[]

In [15]:
x

{'': [], 'grad': []}

In [17]:
params = torch.zeros(2, requires_grad=True)

In [18]:
def func(_data, _params):
    return torch.sum(
        (_params[0] * _data[:, 0] + _params[1] - _data[:, 1]) ** 2)

In [19]:
data1 = torch.tensor([[-1, -1], [1, 3]])
data2 = torch.tensor([[0, 1]])

In [20]:
p1 = params.clone().detach()
p1.requires_grad = True
p2 = params.clone().detach()
p2.requires_grad = True

In [21]:
print(id(params), id(p1), id(p2))
print(params.requires_grad, p1.requires_grad, p2.requires_grad)

2284783490512 2284783498192 2284783499952
True True True


In [22]:
y1 = func(data1, p1)
y2 = func(data2, p2)

In [23]:
y1, y2

(tensor(10., grad_fn=<SumBackward0>), tensor(1., grad_fn=<SumBackward0>))

In [24]:
y1.backward()
y2.backward()

In [25]:
print(params.grad)
print(p1.grad)
print(p2.grad)

None
tensor([-8., -4.])
tensor([ 0., -2.])


In [81]:
val = 0
val += func(data1, p1)
val += func(data2, p2)

In [45]:
p1_ = p1.clone().detach()
p1.requires_grad = True
p1_.grad = p1.grad.clone()

In [46]:
print(p1_.grad)
print(id(p1.grad) == id(p1_.grad))

tensor([-8., -4.])
False


In [50]:
if(p1 != None):
    print('yes')

yes


In [82]:
val.backward()

In [112]:
torch.tensor([]).size()

torch.Size([0])

In [54]:
G = torch.tensor([[0, 1, 0, 1],
                  [1, 0, 1, 0],
                  [0, 1, 0, 1],
                  [1, 0, 1, 0]], dtype=torch.int)

In [55]:
x = torch.arange(G[:, 0].shape[0], dtype=torch.int)

In [56]:
y = ['a', 'b', 'c', 'd']

In [57]:
z = [y[each.item()] for each in x[G[:, 0] == 1]]

In [58]:
z

['b', 'd']

In [59]:
G[:, 0] == 1

tensor([False,  True, False,  True])

In [62]:
def func(a):
    def inner_func(x, y):
        return x + a * y
    return inner_func

In [63]:
a = 0.1
f = func(a)

In [64]:
f(1, 2)

1.2